# Generated by Django 4.2.7 on 2023-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
