# Generated by Django 4.2.7 on 2023-11-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_response_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='completed',
        ),
    ]
